# Generated by Django 6.0.2 on 2026-02-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemdesignrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
