# Generated by Django 6.0.2 on 2026-02-12 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemanalysis',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
